[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-introduction-notebooks"
version = "0.2.2"
description = "Jupyter-Notebooks für die Python-Einführung 2025"
readme = "README.md"
authors = [
  { name = "HS Esslingen", email = "andreas.roessler@hs-esslingen.de" }
]
requires-python = ">=3.8"
dependencies = [
  "notebook",
  "jupyterlab",
  "ipykernel",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["python_introduction"]
include-package-data = true

[tool.setuptools.package-data]
"python_introduction" = ["notebooks/**/*"]

[project.scripts]
python-intro-copy = "python_introduction.copy:main"
